name: visibility_detector_example

publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.13.8'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector:
    path: ../
  # 瀑布流相关依赖
  waterfall_flow: ^3.0.2
  # 滚动监听库
  scrollview_observer: ^1.21.0
  # 视频播放器
  video_player: ^2.8.1
  # 用于生成假数据
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/json/pcas-code.json